## Numpy

In [60]:
import numpy as np

scores = [89,56, 34, 76,89, 98] 
first_arr =np.array(scores) 

print(first_arr) 
print(first_arr.dtype) 



[89 56 34 76 89 98]
int32


## Nested lists with equal length, will be converted into a multidimensional array 

In [61]:
scores_1 = [[34,56,23,89], [11,45,76,34]] 
second_arr = np.array(scores_1) 

In [62]:
print(second_arr)

[[34 56 23 89]
 [11 45 76 34]]


In [69]:
print(second_arr.ndim) # 2
print(second_arr.shape) # (2, 4)
print(second_arr.dtype) #int32

x = np.zeros(10) 
print(x) 
t = np.ones(10)
print(t)

y=np.zeros((4,3)) 

print(y) 
 
np.arange(15) 

2
(2, 4)
int32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere) Batch operations on data can be performed without using for loops, this is called vectorizaton 

In [55]:
np.eye(6) 

scores = [89,56.34, 76,89, 98] 
first_arr =np.array(scores)

print (first_arr) 
print (first_arr * first_arr) 
print (first_arr - first_arr) 
print (1/(first_arr)) 
print (first_arr ** 0.5) 


[89.   56.34 76.   89.   98.  ]
[7921.     3174.1956 5776.     7921.     9604.    ]
[0. 0. 0. 0. 0.]
[0.01123596 0.01774938 0.01315789 0.01123596 0.01020408]
[9.43398113 7.5059976  8.71779789 9.43398113 9.89949494]


## Indexing and Slicing.  you may want to select a subset of your data, for which Numpy array indexing is really useful  


In [59]:
new_arr = np.arange(12)  
print (new_arr[4:9]) #[4 5 6 7 8]

new_arr[4:9] = 99
print(new_arr) 

[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]


## arrays can be treated like matrices 

In [61]:
matrix_arr =np.array([[3,4,5],[6,7,8],[9,5,1]]) 

print (matrix_arr) 
 
print (matrix_arr[0][2]) #first row and third column print (matrix_arr[0,2])


[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5


In [63]:
print (matrix_arr[1])
print (matrix_arr[0][2])


[6 7 8]
5


## 3d arrays -> this is a 2x2x3 array 

In [64]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 

print (three_d_arr) 

print ("returns the second list inside first list {}".format(three_d_arr[0,1])) 



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
returns the second list inside first list [4 5 6]


In [65]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 

In [66]:
print(three_d_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Data processing using Arrays 

In [68]:
mtrices = np.arange(-5,5,1) 
print(mtrices)

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [69]:
x, y = np.meshgrid(mtrices, mtrices)) #mesh grid function takes two 1 d arrays and produces two 2d arrays

In [73]:
print(x)

[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]


In [72]:
print(y)

[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]


## Series. A Series is represented by index on the left and values on the right

In [ ]:
ser

In [36]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

mjp = Series([5,4,3,2,1])
mjp.values # Similar to dictionary. values command return values in a series

ser = Series([5,4,3,2,1,-7,-29], index=['a','b','c','d','e','f','h']) # The index is specified

print(ser[ser > 0]) #Returns only the positive values
np.mean(ser) # you can apply numpy functions to a Serives


player_salary ={'Rooney': 50000, 'Messi': 75000, 'Ronaldo': 85000, 'Fabregas':40000, 'Van persie': 67000}  
player_salary

new_player = Series(player_salary)  # converting a dictionary to a series 
print(new_player)



a    5
b    4
c    3
d    2
e    1
dtype: int64
Rooney        50000
Messi         75000
Ronaldo       85000
Fabregas      40000
Van persie    67000
dtype: int64


 ## Data Frame 
Data frame is a spread sheet like structure, containing ordered collection of columns. Each column can have different value type. Data frame has both row index and column index. 


In [44]:
states = {'State' :['Gujarat', 'Tamil Nadu', ' Andhra', 'Karnataka', 'Kerala'], 
                  'Population': [36, 44, 67,89,34], 
                  'Language' :['Gujarati', 'Tamil', 'Telugu', 'Kannada', 'Malayalam']} 



india = DataFrame(states)   # creating a data frame print(india) 

DataFrame(states, columns=['State', 'Language', 'Population'])  # change the sequence of column index 

State   Language  Population
0     Gujarat   Gujarati          36
1  Tamil Nadu      Tamil          44
2      Andhra     Telugu          67
3   Karnataka    Kannada          89
4      Kerala  Malayalam          34

In [49]:
new_farme = DataFrame(states, columns=['State', 'Language', 'Population', 'Per Capita Income'], index =['a','b','c','d','e']) 
print(new_farme)

        State   Language  Population Per Capita Income
a     Gujarat   Gujarati          36               NaN
b  Tamil Nadu      Tamil          44               NaN
c      Andhra     Telugu          67               NaN
d   Karnataka    Kannada          89               NaN
e      Kerala  Malayalam          34               NaN


In [53]:
print(new_farme.Population)

a    36
b    44
c    67
d    89
e    34
Name: Population, dtype: int64


In [57]:
new_data ={'Modi': {2010: 72, 2012: 78, 2014 : 98},'Rahul': {2010: 55, 2012: 34, 2014: 22}} 
elections = DataFrame(new_data)  
print(elections)  # the outer dict keys are columns and inner dict keys are rows elections.T   # transpose of a data frame inner dict keys are rows 
elections.T   # transpose of a data frame 



      Modi  Rahul
2010    72     55
2012    78     34
2014    98     22


2010  2012  2014
Modi     72    78    98
Rahul    55    34    22

## Dropping entries from an axis 

In [46]:
print(states)
print(india)
states.values
print(new_farme)
new_frame

{'State': ['Gujarat', 'Tamil Nadu', ' Andhra', 'Karnataka', 'Kerala'], 'Population': [36, 44, 67, 89, 34], 'Language': ['Gujarati', 'Tamil', 'Telugu', 'Kannada', 'Malayalam']}
        State  Population   Language
0     Gujarat          36   Gujarati
1  Tamil Nadu          44      Tamil
2      Andhra          67     Telugu
3   Karnataka          89    Kannada
4      Kerala          34  Malayalam
        State   Language  Population Per Capita Income
a     Gujarat   Gujarati          36               NaN
b  Tamil Nadu      Tamil          44               NaN
c      Andhra     Telugu          67               NaN
d   Karnataka    Kannada          89               NaN
e      Kerala  Malayalam          34               NaN


## Data Mungling Basics
## Segment 1 - Filtering and Selecting data

In [72]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## Selecting and retrieving data


In [74]:
series_obj = Series(np.arange(8), index=['row 1', 'row 2','row 3','row 4','row 5', 'row 6', 'row 7', 'row 8']) 
print(series_obj) 

row 1    0
row 2    1
row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
row 8    7
dtype: int32


#### When you write square brackets with an integer index inside them, this tells Python to select and retrieve all records with the specified integer index

In [76]:
print(series_obj[[0,2,4,7]]) 

row 1    0
row 3    2
row 5    4
row 8    7
dtype: int32


In [78]:
np.random.seed(25) 
DF_obj = DataFrame(np.random.rand(36).reshape((6,6)),
                   index=['row 1', 'row 2', 'row 3', 'row 4', 'row 5', 'row 6'],                    
                   columns=['column 1', 'column 2', 'column 3', 'column 4', 'column 5', 'column 6']) 



In [79]:
print(DF_obj)

       column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819


### When you call the .ix[] special indexer, and pass in a set of row and column indexes, this tells Python to select and retrieve only those specific rows and columns. 

In [82]:
DF_obj.loc[['row 2', 'row 5'], ['column 5', 'column 2']] 

column 5  column 2
row 2  0.402366  0.437611
row 5  0.421004  0.559053

## Data slicing -> ['starting label-index':'ending label-index']  
##### Data slicing allows you to select and retrieve all records from the starting label-index, to the  # ending label-index, and every record in between. 

In [91]:
print(DF_obj['row 3':'row 7']) 

       column 1  column 2  column 3  column 4  column 5  column 6
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819


## Segment 2 - Treating missing values 

In [93]:
import numpy as np 
import pandas as pd  
from pandas import Series, DataFrame 

## Figuring out what data is missing

In [96]:
missing = np.nan 
series_obj = Series(['row 1', 'row 2', missing, 'row 4','row 5', 'row 6', missing, 'row 8']) 

print(series_obj) 


0    row 1
1    row 2
2      NaN
3    row 4
4    row 5
5    row 6
6      NaN
7    row 8
dtype: object


### The isnull() method returns a Boolean value that describes (True or False) whether an element in a Pandas object is a null value. 

In [97]:
print(series_obj.isnull()) 

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
dtype: bool


## Filling in for missing values 

In [101]:

DF_obj = DataFrame(np.random.randn(36).reshape(6,6)) 
print(DF_obj) 


          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723 -0.169196
2 -0.658381 -0.196024  0.177552  0.032294  1.303258 -0.539484
3  0.529918  0.382797  1.800623  2.513618 -0.245011  0.208728
4 -0.300852  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


In [104]:
DF_obj.iloc[3:5, 0] = missing 

DF_obj.iloc[1:4, 5] = missing 

print(DF_obj) 


          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723       NaN
2 -0.658381 -0.196024  0.177552  0.032294  1.303258       NaN
3       NaN  0.382797  1.800623  2.513618 -0.245011       NaN
4       NaN  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


#### The fillna method() finds each missing value from within a Pandas object and fills it with the  # numeric value that you've passed in using: object_name.fillna(numeric value) 

In [109]:
filled_DF = DF_obj.fillna(0)
print(filled_DF) 

          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723  0.000000
2 -0.658381 -0.196024  0.177552  0.032294  1.303258  0.000000
3  0.000000  0.382797  1.800623  2.513618 -0.245011  0.000000
4  0.000000  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


In [110]:
print(DF_obj)

          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723       NaN
2 -0.658381 -0.196024  0.177552  0.032294  1.303258       NaN
3       NaN  0.382797  1.800623  2.513618 -0.245011       NaN
4       NaN  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


#### You can pass a dictionary into the .fillna() method. The method will then fill in missing values from each column Series (as designated by the dictionary key) with its own unique value (as specified in the corresponding dictionary value

In [108]:
filled_DF = DF_obj.fillna({0: 0.1, 5: 1.25}) 
print(filled_DF) 



          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723  1.250000
2 -0.658381 -0.196024  0.177552  0.032294  1.303258  1.250000
3  0.100000  0.382797  1.800623  2.513618 -0.245011  1.250000
4  0.100000  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


#### You can also pass in the method='ffill' arguement, and the .fillna() method will fill-forward any  # missing values with values from the last non-null element in the column Series

In [113]:
print(DF_obj)
fill_DF = DF_obj.fillna(method='ffill') 
print(fill_DF) 




          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723       NaN
2 -0.658381 -0.196024  0.177552  0.032294  1.303258       NaN
3       NaN  0.382797  1.800623  2.513618 -0.245011       NaN
4       NaN  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294
          0         1         2         3         4         5
0  1.020364 -0.587397  0.048037  0.560169  1.424193 -0.003191
1 -0.297766  0.232724  0.671954 -1.346282 -0.601723 -0.003191
2 -0.658381 -0.196024  0.177552  0.032294  1.303258 -0.003191
3 -0.658381  0.382797  1.800623  2.513618 -0.245011 -0.003191
4 -0.658381  0.152992  0.030979 -0.324954 -0.777273 -0.337442
5 -2.020510  1.419771 -0.741890 -1.559918  0.966290 -0.182294


### Counting missing values 

In [114]:
np.random.seed(25) 

In [123]:
DF_obj = DataFrame(np.random.randn(36).reshape(6,6)) 

DF_obj.iloc[3:5, 0] = missing 
DF_obj.iloc[1:4, 5] = missing 
print(DF_obj) 

          0         1         2         3         4         5
0  0.164135 -0.673210 -0.168668 -0.541845 -0.352464  1.688785
1  0.092362  1.121011 -0.451224  0.872053 -1.142141       NaN
2  0.930692 -0.177927 -2.158403 -0.289260 -0.904782       NaN
3       NaN  0.649388  0.019125 -0.977803 -1.972866       NaN
4       NaN -3.049890  0.394720 -1.947339  0.533330  0.379163
5  2.040071  0.307235 -0.669187 -0.196576  0.922861  1.727249


### To generate a count of how many missing values a DataFrame has per column, just call the .isnull() method off of the object, and then call the .sum() method off of the matrix of Boolean values it returns. 

In [122]:
DF_obj.isnull().sum()

0    2
1    0
2    0
3    0
4    0
5    3
dtype: int64

### Filtering out missing values. 
### To identify and drop all rows from a DataFrame that contain ANY missing values, simply call the .dropna() method off of the DataFrame object. NOTE: If you wanted to drop columns that contain any missing values, you'd just pass in the axis=1 argument to select and search the DataFrame by columns, instead of by row


In [125]:
print(DF_obj) 
DF_no_NaN = DF_obj.dropna(axis=1)

print(DF_no_NaN) 

          0         1         2         3         4         5
0  0.164135 -0.673210 -0.168668 -0.541845 -0.352464  1.688785
1  0.092362  1.121011 -0.451224  0.872053 -1.142141       NaN
2  0.930692 -0.177927 -2.158403 -0.289260 -0.904782       NaN
3       NaN  0.649388  0.019125 -0.977803 -1.972866       NaN
4       NaN -3.049890  0.394720 -1.947339  0.533330  0.379163
5  2.040071  0.307235 -0.669187 -0.196576  0.922861  1.727249
          1         2         3         4
0 -0.673210 -0.168668 -0.541845 -0.352464
1  1.121011 -0.451224  0.872053 -1.142141
2 -0.177927 -2.158403 -0.289260 -0.904782
3  0.649388  0.019125 -0.977803 -1.972866
4 -3.049890  0.394720 -1.947339  0.533330
5  0.307235 -0.669187 -0.196576  0.922861


### To identify and drop only the rows from a DataFrame that contain ALL missing values, simply call the .dropna() method off of the DataFrame object, and pass in the how='all' argument. 

In [126]:
print(DF_obj)

          0         1         2         3         4         5
0  0.164135 -0.673210 -0.168668 -0.541845 -0.352464  1.688785
1  0.092362  1.121011 -0.451224  0.872053 -1.142141       NaN
2  0.930692 -0.177927 -2.158403 -0.289260 -0.904782       NaN
3       NaN  0.649388  0.019125 -0.977803 -1.972866       NaN
4       NaN -3.049890  0.394720 -1.947339  0.533330  0.379163
5  2.040071  0.307235 -0.669187 -0.196576  0.922861  1.727249


In [134]:
print(DF_obj.dropna(how='all')) 
dropall = DF_obj.dropna(how='all')

          0         1         2         3         4         5
0  0.164135 -0.673210 -0.168668 -0.541845 -0.352464  1.688785
1  0.092362  1.121011 -0.451224  0.872053 -1.142141       NaN
2  0.930692 -0.177927 -2.158403 -0.289260 -0.904782       NaN
3       NaN  0.649388  0.019125 -0.977803 -1.972866       NaN
4       NaN -3.049890  0.394720 -1.947339  0.533330  0.379163
5  2.040071  0.307235 -0.669187 -0.196576  0.922861  1.727249


In [135]:
print(dropall)

          0         1         2         3         4         5
0  0.164135 -0.673210 -0.168668 -0.541845 -0.352464  1.688785
1  0.092362  1.121011 -0.451224  0.872053 -1.142141       NaN
2  0.930692 -0.177927 -2.158403 -0.289260 -0.904782       NaN
3       NaN  0.649388  0.019125 -0.977803 -1.972866       NaN
4       NaN -3.049890  0.394720 -1.947339  0.533330  0.379163
5  2.040071  0.307235 -0.669187 -0.196576  0.922861  1.727249


### Segment 3 - Removing duplicates. This is for both column and nows as well.

In [136]:
import numpy as np 
import pandas as pd 
from pandas import Series, DataFrame 

In [137]:
DF_obj1 = DataFrame({'column 1': [1, 1, 2, 2, 3, 3, 3], 
                     'column 2': ['a', 'a', 'b', 'b', 'c', 'c', 'c'],                   
                     'column 3': ['A', 'A', 'B', 'B', 'C', 'C', 'C']})

print(DF_obj1) 


   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C


### The duplicated() method searches each row in the DataFrame, and returns a True or False value to indicate whether it is a duplicate of another row found earlier in the DataFrame. 


### To drop all duplicate rows, just call the drop_duplicates() method off of the DataFrame. 




In [139]:
dup =  DF_obj1.drop_duplicates()
print(dup)



   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C


In [140]:
print(DF_obj1)

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C


In [145]:
DF_obj2 = DataFrame({'column 1': [1, 1, 2, 2, 3, 3, 3], 
                     'column 2': ['a', 'a', 'b', 'b', 'c', 'c', 'c'], 
                     'column 3': ['A', 'A', 'B', 'B', 'C', 'D', 'C']}) 

print(DF_obj2)

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        D
6         3        c        C


### To drop the rows that have duplicates in only one column Series, just call the drop_duplicates() method of the DataFrame, and pass in the label-index of the column you want the de-duplication to be based on. This method will drops all rows that have duplicates in the column you specify. 

 

In [147]:

dup2 = DF_obj2.drop_duplicates(['column 3'])
print(DF_obj2)


   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        D
6         3        c        C


In [148]:
print(dup2)

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        D


### Concatenating and transforming data 

In [150]:
DF_obj3 = pd.DataFrame(np.arange(36).reshape(6,6))
print(DF_obj3) 

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35


In [152]:
DF_obj_4 = pd.DataFrame(np.arange(15).reshape(5,3)) 
print(DF_obj_4) 

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14


### Concatenating data --->pd.concat([left_object, right_object], axis=1) 





### The concat() method joins data from seperate sources into one combined data table. If you want to join objects based on their row index values, just call the pd.concat() method on the objects you want joined, and then pass in the axis=1 argument. The axis=1 argument tells Python to concatenate the DataFrames by adding columns (in other words, joining on the row index values). 

In [155]:
joined = pd.concat([DF_obj3, DF_obj_4], axis =1) 

print(joined)


    0   1   2   3   4   5     0     1     2
0   0   1   2   3   4   5   0.0   1.0   2.0
1   6   7   8   9  10  11   3.0   4.0   5.0
2  12  13  14  15  16  17   6.0   7.0   8.0
3  18  19  20  21  22  23   9.0  10.0  11.0
4  24  25  26  27  28  29  12.0  13.0  14.0
5  30  31  32  33  34  35   NaN   NaN   NaN


In [156]:
print(DF_obj3) 
print(DF_obj_4) 

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35
    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14


### Transforming data  and Dropping data 


In [162]:
print(DF_obj3) 
drp =DF_obj3.drop([0,2])

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35


In [163]:
print(drp)

    0   1   2   3   4   5
1   6   7   8   9  10  11
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35


In [165]:
drop2 = DF_obj3.drop([0,2], axis=1)


print(drop2)

In [169]:
print(DF_obj3)

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35


### Adding data 

In [174]:
series_obj = Series(np.arange(6)) 
series_obj.name = "added_variable" 
print(DF_obj.drop([0,2], axis=1)) 

          1         3         4         5
0 -0.673210 -0.541845 -0.352464  1.688785
1  1.121011  0.872053 -1.142141       NaN
2 -0.177927 -0.289260 -0.904782       NaN
3  0.649388 -0.977803 -1.972866       NaN
4 -3.049890 -1.947339  0.533330  0.379163
5  0.307235 -0.196576  0.922861  1.727249


### You can use .join() method to join two data sources into one. The .join() method works by joining the two sources on their row index values: variable_added = DataFrame.join(DF_obj, series_obj) 

## Sorting data 
## To sort rows in a DataFrame, either in ascending or descending order, call the .sort_values()  # method off of the DataFrame, and pass in the by argument to specify the column index upon which the DataFrame should be sorted.  
#### DF_sorted = DF_obj.sort_values(by=[5], ascending=[False]) print(DF_sorted) 


## Grouping and data aggregation 

### filepath = 'mtcars.csv' cars = pd.read_csv(filepath) cars.columns = ['car_names','mpg','cyl','disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'] print(cars.head()) 