## Numpy Array

1. Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6,7,8,9]
type(l)

list

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
type(arr)

numpy.ndarray

### Attributes of by numpy ndarray object
1. ndim
2. dtype
3. shape
4. size 
5. itemsize

In [4]:
arr.ndim

1

In [5]:
list2d = [[1,2,3],[4,5,6],[7,8,9]]
list2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr2d = np.array(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2d.ndim

2

In [8]:
list3d = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
list3d

In [9]:
arr3d = np.array(list3d)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
arr3d.ndim

3

In [11]:
arr3d[0][1]

array([4, 5, 6])

In [12]:
arr3d.shape

(2, 3, 3)

In [13]:
arr3d.size

18

In [14]:
arr3d.dtype

dtype('int32')

In [15]:
arr3d.itemsize

4

In [16]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85] 
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [18]:
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)
print(np_weight)

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


### DataType Precedence

In [25]:
myli = [100,'sakeeb',1000.000]
arr_li = np.array(myli)
type(arr_li)

numpy.ndarray

In [26]:
arr_li.dtype

dtype('<U11')

In [23]:
np_height.dtype

dtype('float64')

In [24]:
arr3d.dtype

dtype('int32')

### Special Functions
1. arange()
2. zeros()
3. ones()
4. eye()
5. empty()
6. copy()
7. reshape()

In [27]:
arrseq = np.arange(10)
arrseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arrseq = np.arange(1,11)
arrseq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arrseq = np.arange(1,11,2)
arrseq

array([1, 3, 5, 7, 9])

In [31]:
arrzero = np.zeros(10)
arrzero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
arrzero = np.zeros([3,3])
arrzero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arrzero = np.zeros([2,3,3])
arrzero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
arrone = np.ones(10)
arrone

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arrone = np.ones([3,3])
arrone

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
arrone = np.ones([2,3,3])
arrone

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
arreye = np.eye(3)
arreye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arreye = np.eye(4)
arreye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
arrempty = np.empty([3,3])
arrempty

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arrempty = np.empty(3)
arrempty

array([1., 1., 1.])

In [43]:
arrempty = np.empty([4,5])
arrempty

array([[2.76518058e-316, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.69118108e-306],
       [5.30276956e+180, 3.31033942e-033, 4.57842046e-071,
        5.06636305e-086, 3.35960142e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 9.04729241e-067],
       [6.10342681e+170, 3.59663871e+175, 1.73708971e-047,
        5.69130203e-143, 1.50008929e+248]])

In [44]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
id(arr)

89302640

In [46]:
arr1 = arr

In [47]:
id(arr1)

89302640

In [48]:
arr1[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [49]:
arr1 = np.copy(arr)

In [50]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [51]:
arr1

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [52]:
arr1[0] = 200

In [53]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [54]:
arr1

array([200,   2,   3,   4,   5,   6,   7,   8,   9])

In [56]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arrreshape = arr.reshape(9,1)

In [60]:
arrreshape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [61]:
arrreshape = np.arange(12).reshape(3,4)
arrreshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
arrreshape = np.arange(12).reshape(2,2,3)
print(arrreshape)
dept1 = arrreshape[0]
dept2 = arrreshape[1]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [64]:
dept1

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
dept2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
flattenarr = np.ravel(arrreshape)
flattenarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
li = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]
res = []
for i in li:
    res.append(i*2)
res

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]

In [71]:
flattenarr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [72]:
flattenarr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [73]:
flattenarr/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2])

In [76]:
bmi = (np_weight/np_height)**2
bmi

array([1906.46644171, 2719.59461237, 2738.96947832, 2369.80356898,
       2057.33861496, 2285.87363039])

In [75]:
bmi[bmi<25]

array([23.34925219, 23.87257618])

### random number generation
1. uniform distribution  np.random.rand()
2. normal distribution   np.random.randn()
3. random int number     np.random.randint()