## Input Dataset With Specified Classes as Positive and Negative
![title](img.jpg)

In [1]:
# K-Nearest Neighbors (K-NN)
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('knn_dataset.csv')
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values

In [3]:
X

array([[2, 4],
       [4, 2],
       [4, 4],
       [4, 6],
       [6, 2],
       [6, 4]], dtype=int64)

In [4]:
y

array([1, 1, 0, 1, 0, 1], dtype=int64)

In [4]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [5]:
# Predicting the Test set results
y_pred = classifier.predict(X)

In [6]:
y_pred

array([1, 0, 1, 1, 1, 0], dtype=int64)

In [7]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_pred)
print(cm)

[[0 2]
 [2 2]]


In [11]:
x_new = np.array([[6,6]])

In [12]:
y_pred_new = classifier.predict(x_new)

In [14]:
y_pred_new

array([1], dtype=int64)

In [13]:
if y_pred_new[0] == 0:
    print('The Class for the point (6,6) is NEGATIVE')
else:
    print('The Class for the point (6,6) is POSITIVE')

The Class for the point (6,6) is POSITIVE


## Distance Weighted KNN Classifier

In [15]:
dist_classifier = KNeighborsClassifier(n_neighbors = 3, weights='distance', metric = 'minkowski', p = 2)
dist_classifier.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='distance')

In [16]:
# Predicting the Test set results
y_pred_dist = dist_classifier.predict(X)

In [17]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_pred_dist)
print(cm)

[[2 0]
 [0 4]]


In [18]:
x_new = np.array([[6,6]])
y_pred_new = classifier.predict(x_new)

In [38]:
if y_pred_new[0] == 0:
    print('The Class for the point (6,6) is NEGATIVE')
else:
    print('The Class for the point (6,6) is POSITIVE')

The Class for the point (6,6) is POSITIVE


## Position and Predicted Class of New Point (6,6)
![title](finalimg.jpg)